package com.jamon.qaseladmin.model;


import lombok.Data;

@Data
public class QaselUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qasel_user.id
     *
     * @mbg.generated Tue Apr 12 21:31:22 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qasel_user.nickname
     *
     * @mbg.generated Tue Apr 12 21:31:22 CST 2022
     */
    private String nickname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qasel_user.phone
     *
     * @mbg.generated Tue Apr 12 21:31:22 CST 2022
     */
    private Integer phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qasel_user.address
     *
     * @mbg.generated Tue Apr 12 21:31:22 CST 2022
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qasel_user.password
     *
     * @mbg.generated Tue Apr 12 21:31:22 CST 2022
     */
    private String password;
}