package com.jamon.qaseluser.model;

public class AnswerText {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column answer_text.id
     *
     * @mbg.generated Wed Apr 13 21:00:57 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column answer_text.qid
     *
     * @mbg.generated Wed Apr 13 21:00:57 CST 2022
     */
    private Integer qid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column answer_text.answer
     *
     * @mbg.generated Wed Apr 13 21:00:57 CST 2022
     */
    private String answer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column answer_text.score
     *
     * @mbg.generated Wed Apr 13 21:00:57 CST 2022
     */
    private Float score;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column answer_text.label
     *
     * @mbg.generated Wed Apr 13 21:00:57 CST 2022
     */
    private Integer label;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column answer_text.id
     *
     * @return the value of answer_text.id
     *
     * @mbg.generated Wed Apr 13 21:00:57 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column answer_text.id
     *
     * @param id the value for answer_text.id
     *
     * @mbg.generated Wed Apr 13 21:00:57 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column answer_text.qid
     *
     * @return the value of answer_text.qid
     *
     * @mbg.generated Wed Apr 13 21:00:57 CST 2022
     */
    public Integer getQid() {
        return qid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column answer_text.qid
     *
     * @param qid the value for answer_text.qid
     *
     * @mbg.generated Wed Apr 13 21:00:57 CST 2022
     */
    public void setQid(Integer qid) {
        this.qid = qid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column answer_text.answer
     *
     * @return the value of answer_text.answer
     *
     * @mbg.generated Wed Apr 13 21:00:57 CST 2022
     */
    public String getAnswer() {
        return answer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column answer_text.answer
     *
     * @param answer the value for answer_text.answer
     *
     * @mbg.generated Wed Apr 13 21:00:57 CST 2022
     */
    public void setAnswer(String answer) {
        this.answer = answer == null ? null : answer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column answer_text.score
     *
     * @return the value of answer_text.score
     *
     * @mbg.generated Wed Apr 13 21:00:57 CST 2022
     */
    public Float getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column answer_text.score
     *
     * @param score the value for answer_text.score
     *
     * @mbg.generated Wed Apr 13 21:00:57 CST 2022
     */
    public void setScore(Float score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column answer_text.label
     *
     * @return the value of answer_text.label
     *
     * @mbg.generated Wed Apr 13 21:00:57 CST 2022
     */
    public Integer getLabel() {
        return label;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column answer_text.label
     *
     * @param label the value for answer_text.label
     *
     * @mbg.generated Wed Apr 13 21:00:57 CST 2022
     */
    public void setLabel(Integer label) {
        this.label = label;
    }
}