package com.jamon.qaseluser.model;

public class QuestionText {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question_text.id
     *
     * @mbg.generated Wed Apr 13 10:59:13 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question_text.question
     *
     * @mbg.generated Wed Apr 13 10:59:13 CST 2022
     */
    private String question;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question_text.label
     *
     * @mbg.generated Wed Apr 13 10:59:13 CST 2022
     */
    private Integer label;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_text.id
     *
     * @return the value of question_text.id
     *
     * @mbg.generated Wed Apr 13 10:59:13 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_text.id
     *
     * @param id the value for question_text.id
     *
     * @mbg.generated Wed Apr 13 10:59:13 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_text.question
     *
     * @return the value of question_text.question
     *
     * @mbg.generated Wed Apr 13 10:59:13 CST 2022
     */
    public String getQuestion() {
        return question;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_text.question
     *
     * @param question the value for question_text.question
     *
     * @mbg.generated Wed Apr 13 10:59:13 CST 2022
     */
    public void setQuestion(String question) {
        this.question = question == null ? null : question.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_text.label
     *
     * @return the value of question_text.label
     *
     * @mbg.generated Wed Apr 13 10:59:13 CST 2022
     */
    public Integer getLabel() {
        return label;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_text.label
     *
     * @param label the value for question_text.label
     *
     * @mbg.generated Wed Apr 13 10:59:13 CST 2022
     */
    public void setLabel(Integer label) {
        this.label = label;
    }
}