package com.jamon.qaseluser.mapper;

import com.jamon.qaseluser.model.AnswerText;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface AnswerTextMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table answer_text
     *
     * @mbg.generated Wed Apr 13 21:00:57 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table answer_text
     *
     * @mbg.generated Wed Apr 13 21:00:57 CST 2022
     */
    int insert(AnswerText record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table answer_text
     *
     * @mbg.generated Wed Apr 13 21:00:57 CST 2022
     */
    int insertSelective(AnswerText record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table answer_text
     *
     * @mbg.generated Wed Apr 13 21:00:57 CST 2022
     */
    AnswerText selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table answer_text
     *
     * @mbg.generated Wed Apr 13 21:00:57 CST 2022
     */
    int updateByPrimaryKeySelective(AnswerText record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table answer_text
     *
     * @mbg.generated Wed Apr 13 21:00:57 CST 2022
     */
    int updateByPrimaryKey(AnswerText record);

    List<AnswerText> selectAllByQid(@Param("qid") Integer qid);
}