package com.jamon.qaseluser.mapper;

import com.jamon.qaseluser.model.QuestionText;
import com.jamon.qaseluser.model.QuestionVO;
import com.jamon.qaseluser.model.request.SearchQuestionRequest;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface QuestionTextMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_text
     *
     * @mbg.generated Wed Apr 13 10:59:13 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_text
     *
     * @mbg.generated Wed Apr 13 10:59:13 CST 2022
     */
    int insert(QuestionText record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_text
     *
     * @mbg.generated Wed Apr 13 10:59:13 CST 2022
     */
    int insertSelective(QuestionText record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_text
     *
     * @mbg.generated Wed Apr 13 10:59:13 CST 2022
     */
    QuestionText selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_text
     *
     * @mbg.generated Wed Apr 13 10:59:13 CST 2022
     */
    int updateByPrimaryKeySelective(QuestionText record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_text
     *
     * @mbg.generated Wed Apr 13 10:59:13 CST 2022
     */
    int updateByPrimaryKey(QuestionText record);

    //    获取数据库中所有问题
    List<QuestionText> getAllQuestion();

    List<QuestionVO> searchQuestion(@Param("request") SearchQuestionRequest request);
}