spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ansel
    username: root
    password: 123456


server:
  port: 7090

mybatis:
  mapper-locations: classpath:./mapper/*.xml

#分页插件
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
  #pageSize=0 返回所有
  pageSizeZero: true



