package com.jamon.qaseladmin.mapper;

import com.jamon.qaseladmin.model.AnswerText;
import com.jamon.qaseladmin.model.request.AddAnswerRequest;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface AnswerTextMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table answer_text
     *
     * @mbg.generated Tue Apr 12 20:52:08 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table answer_text
     *
     * @mbg.generated Tue Apr 12 20:52:08 CST 2022
     */
    int insert(AddAnswerRequest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table answer_text
     *
     * @mbg.generated Tue Apr 12 20:52:08 CST 2022
     */
    int insertSelective(AnswerText record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table answer_text
     *
     * @mbg.generated Tue Apr 12 20:52:08 CST 2022
     */
    AnswerText selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table answer_text
     *
     * @mbg.generated Tue Apr 12 20:52:08 CST 2022
     */
    int updateByPrimaryKeySelective(AnswerText record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table answer_text
     *
     * @mbg.generated Tue Apr 12 20:52:08 CST 2022
     */
    int updateByPrimaryKey(AnswerText record);

    List<AnswerText>  selectAllByQid(@Param("qid") Integer qid);
}