package com.jamon.qaseladmin.mapper;

import com.jamon.qaseladmin.model.QaselUser;

public interface QaselUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qasel_user
     *
     * @mbg.generated Tue Apr 12 21:31:22 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qasel_user
     *
     * @mbg.generated Tue Apr 12 21:31:22 CST 2022
     */
    int insert(QaselUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qasel_user
     *
     * @mbg.generated Tue Apr 12 21:31:22 CST 2022
     */
    int insertSelective(QaselUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qasel_user
     *
     * @mbg.generated Tue Apr 12 21:31:22 CST 2022
     */
    QaselUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qasel_user
     *
     * @mbg.generated Tue Apr 12 21:31:22 CST 2022
     */
    int updateByPrimaryKeySelective(QaselUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qasel_user
     *
     * @mbg.generated Tue Apr 12 21:31:22 CST 2022
     */
    int updateByPrimaryKey(QaselUser record);
}